server:
   port: 81
   tomcat:
     uri-encoding: UTF-8

banner:
   charset: UTF-8

spring:
   profiles:
      active: dev
   http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/sb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&characterEncoding=utf8&useSSL=true
      username: root
      password: abc123
      driver-class-name: com.mysql.jdbc.Driver
   freemarker:
     template-loader-path: classpath:/templates/
     cache: false
     charset: utf-8
     check-template-location: true
     content-type: text/html
     expose-request-attributes: true
     expose-session-attributes: true
     request-context-attribute: true
     suffix: .ftl
   rabbitmq:
     host: 127.0.0.1
     port: 5672
     virtual-host: /v
     username: admin
     password: admin

   redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     password:
     pool:
       max-active: 8
       max-wait: 60
       min-idle: 0
     timeout: 0
   session:
     store-type:
     redis:
       namespace: fuckredis
       flush-mode: on_save



logging:
  level:
     root: WARN
     org.springframework.web: DEBUG
  file: my.log
  pattern:
     console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
     file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"

sodbvi:
   secret: ${random.value}
   bignumber: ${random.long}
   uuid: ${random.uuid}
   number:
      less:
         than:
            ten: ${random.int(10)}
      in:
         range: ${random.int[1024,65536]}

mybatis:
  type-aliases-package: com.sodbvi.springboot.domain
  mapper-locations: classpath:mapper/*.xml


