com:
   sodbvi:
      name: sodbvi
      msg: 啊斯蒂芬阿德法撒旦法
      message: message is ${com.sodbvi.name}  ${com.sodbvi.msg}
spring:
   redis:
     database: 0
     host: 123.207.178.189
     port: 6385
     password: hixianchang
     pool:
       max-active: 8
       max-wait: 60
       min-idle: 0
     timeout: 0
   session:
     store-type: redis
     redis:
       namespace: fuck
       flush-mode: on_save