com:
   sodbvi:
      name: sodbvi
      msg: 啊斯蒂芬阿德法撒旦法
      message: message is ${com.sodbvi.name}  ${com.sodbvi.msg}
spring:
   redis:
     database: 0
     host: 1.1.1.1
     port: 0000
     password: xxxxx
     pool:
       max-active: 8
       max-wait: 60
       min-idle: 0
     timeout: 0